noun = input("Put in a noun : ")
Adjective1 = input("Put in an adjective : ")
Verb1 = input("Put in a verb : ")
Verb2 = input("Put in a verb : ")
Verb3 = input("Put in a verb : ")
place1 = input("Put in a place : ")
place2 = input("Put in a place : ")
place3 = input("Put in a place : ")
feeling1 = input("Put in a feeling : ")
feeling2 = input("Put in a feeling : ")
thing = input("Put in a thing or an object :  ")

print("As a %s you have to be %s and do stuff like %s, %s, and %s" % (noun, Adjective1, Verb1, Verb2, Verb3))
print("You get to go to places like %s, %s, and %s. " % (place1, place2, place3))
print("You might feel %s or %s but remember to not forget about the glorious %s" % (feeling1, feeling2, thing))
